# Configuración de la base de datos H2
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

# Mostrar la consola de H2
spring.h2.console.enabled=true

# Configuración de JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Clave de API para Google Maps 
google.api.key=AIzaSyDvT66VQ2YuyfZhp1ymuf8-H_3eo6vT9oU

# Configuracion del servidor
server.port=8080

# Configuración de logs detallados para Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuración adicional
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
